server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: Lyra
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
